package com.thiaguinho.controlebar;

import android.app.AlertDialog;
import android.app.DatePickerDialog;
import android.content.Intent;
import android.database.Cursor;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.os.Bundle;
import android.text.InputType;
import android.view.Gravity;
import android.view.View;
import android.view.ViewGroup;
import android.widget.*;

import androidx.activity.result.ActivityResultLauncher;
import androidx.activity.result.contract.ActivityResultContracts;
import androidx.appcompat.app.AppCompatActivity;

import org.json.JSONArray;
import org.json.JSONObject;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.nio.charset.StandardCharsets;
import java.text.SimpleDateFormat;
import java.util.*;

public class MainActivity extends AppCompatActivity {
    private static final int NAV_H=64;
    private DatabaseHelper db;
    private LicenseManager license;
    private TextView licenseStatus;
    private LinearLayout root,content,nav;
    private ScrollView scroll;
    private final JSONArray cart=new JSONArray();
    private final Deque<Runnable> backStack=new ArrayDeque<>();
    private boolean suppressHistory=false;
    private Runnable currentScreen=null;
    private final SimpleDateFormat iso=new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss",Locale.US);
    private final SimpleDateFormat day=new SimpleDateFormat("yyyy-MM-dd",Locale.US);
    private final SimpleDateFormat br=new SimpleDateFormat("dd/MM/yyyy HH:mm",new Locale("pt","BR"));

    private final ActivityResultLauncher<String> exportLauncher=registerForActivityResult(new ActivityResultContracts.CreateDocument("application/json"),uri->{if(uri!=null)exportTo(uri);});
    private final ActivityResultLauncher<String[]> importLauncher=registerForActivityResult(new ActivityResultContracts.OpenDocument(),uri->{if(uri!=null)confirmImport(uri);});

    @Override protected void onCreate(Bundle b){
        super.onCreate(b);
        db=new DatabaseHelper(this);
        license=new LicenseManager(this);
        if(db.productCount()>0)license.startTrialIfNeeded();
        buildShell();
        updateLicenseStatus();
        if(license.isExpired())showLockedScreen(false);else showDashboard(false);
    }
    @Override protected void onResume(){
        super.onResume();
        if(license!=null&&root!=null){updateLicenseStatus();if(license.isExpired()&&currentScreen!=null)showLockedScreen(false);}
    }
    @Override public void onBackPressed(){if(!backStack.isEmpty()){Runnable r=backStack.pop();suppressHistory=true;r.run();suppressHistory=false;}else super.onBackPressed();}

    private void buildShell(){
        root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(C.bg);root.addView(header());
        scroll=new ScrollView(this);scroll.setFillViewport(true);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(12),dp(12),dp(12),dp(90));scroll.addView(content,new ScrollView.LayoutParams(-1,-2));root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
        nav=new LinearLayout(this);nav.setOrientation(LinearLayout.HORIZONTAL);nav.setPadding(dp(5),dp(5),dp(5),dp(5));nav.setBackgroundColor(Color.WHITE);nav.setElevation(dp(10));
        addNav("Início",()->openProtected(()->showDashboard(true)));addNav("Venda",()->openProtected(()->showSale(true)));addNav("Estoque",()->openProtected(()->showProducts("",true)));addNav("Relatórios",()->openProtected(()->showReports(true)));addNav("Mais",()->showMore(true));root.addView(nav,new LinearLayout.LayoutParams(-1,dp(NAV_H)));setContentView(root);
    }

    private View header(){
        LinearLayout h=new LinearLayout(this);h.setOrientation(LinearLayout.HORIZONTAL);h.setGravity(Gravity.CENTER_VERTICAL);h.setPadding(dp(14),dp(14),dp(10),dp(14));h.setBackgroundColor(C.dark);
        LinearLayout t=new LinearLayout(this);t.setOrientation(LinearLayout.VERTICAL);t.addView(tv("Controle do Bar",21,true,Color.WHITE));t.addView(tv("Vendas • Estoque • Relatórios",12,false,0xFFCBD5E1));h.addView(t,new LinearLayout.LayoutParams(0,-2,1));
        licenseStatus=tv("",11,true,Color.WHITE);licenseStatus.setGravity(Gravity.CENTER);licenseStatus.setPadding(dp(9),0,dp(9),0);licenseStatus.setBackground(bg(C.orange,C.orange,999));licenseStatus.setOnClickListener(v->{if(!license.isPro())showUnlockDialog();else toast("Versão PRO ativa neste aparelho.");});LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-2,dp(38));lp.setMargins(0,0,dp(7),0);h.addView(licenseStatus,lp);
        Button help=button("Ajuda",C.blue);help.setOnClickListener(v->startActivity(new Intent(this,GuideActivity.class)));h.addView(help,new LinearLayout.LayoutParams(dp(78),dp(44)));return h;
    }
    private void addNav(String label,Runnable r){Button b=button(label,C.nav);b.setTextSize(10);b.setOnClickListener(v->r.run());LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,-1,1);p.setMargins(dp(2),0,dp(2),0);nav.addView(b,p);}

    private boolean canUse(){return license==null||!license.isExpired();}
    private void openProtected(Runnable action){if(canUse())action.run();else showLockedScreen(false);}
    private void updateLicenseStatus(){if(licenseStatus==null||license==null)return;licenseStatus.setText(license.statusLabel());int color=license.isPro()?C.green:(license.isExpired()?C.red:C.orange);licenseStatus.setBackground(bg(color,color,999));}
    private void addLicenseBanner(){if(license==null||license.isPro())return;LinearLayout box=card(license.isExpired()?0xFFFFF1F2:0xFFFFFBEB,license.isExpired()?C.red:C.orange);box.addView(tv(license.isExpired()?"DEMONSTRAÇÃO ENCERRADA":"VERSÃO DE DEMONSTRAÇÃO",14,true,license.isExpired()?C.red:C.orange));String message=!license.isTrialStarted()?"Os 3 dias começam somente quando o primeiro produto for cadastrado.":license.isExpired()?"O prazo terminou. Seus produtos, estoque e vendas continuam salvos.":"Restam "+license.daysRemaining()+" dia(s). O prazo começou em "+license.formattedStart()+".";box.addView(tv(message,13,false,C.text));if(license.isExpired()){Button unlock=button("Desbloquear versão PRO",C.green);unlock.setOnClickListener(v->showUnlockDialog());box.addView(unlock,full());}content.addView(box,full());}

    private void prepare(String title,Runnable current,boolean history){if(history&&!suppressHistory&&currentScreen!=null)backStack.push(currentScreen);currentScreen=current;content.removeAllViews();scroll.scrollTo(0,0);LinearLayout top=horizontal(false);Button back=button("‹ Voltar",C.gray);back.setOnClickListener(v->onBackPressed());top.addView(back,new LinearLayout.LayoutParams(dp(92),dp(44)));TextView x=tv(title,22,true,C.text);x.setGravity(Gravity.CENTER_VERTICAL);LinearLayout.LayoutParams xp=new LinearLayout.LayoutParams(0,dp(44),1);xp.setMargins(dp(8),0,0,0);top.addView(x,xp);content.addView(top,full());}

    private void showDashboard(boolean history){if(!canUse()){showLockedScreen(false);return;}prepare("Visão geral",()->showDashboard(false),history);addLicenseBanner();String today=day.format(new Date());LinearLayout stats=responsiveRow();stats.addView(stat("Vendas hoje",String.valueOf(db.dailyCount(today))),cell());stats.addView(stat("Total hoje",DatabaseHelper.money(db.dailyTotal(today))),cell());content.addView(stats,full());Cursor low=db.lowStockProducts();int lowCount=low.getCount();low.close();View lowCard=stat("Itens para comprar",String.valueOf(lowCount));lowCard.setOnClickListener(v->showBuyReport(true));content.addView(lowCard,full());content.addView(section("Ações rápidas"));LinearLayout actions=responsiveRow();Button sale=button("Nova venda",C.green);sale.setOnClickListener(v->showSale(true));Button product=button("Cadastrar produto",C.blue);product.setOnClickListener(v->showProductForm(null,true));actions.addView(sale,cell());actions.addView(product,cell());content.addView(actions,full());Button reports=button("Abrir relatórios",C.orange);reports.setOnClickListener(v->showReports(true));content.addView(reports,full());}

    private void showProducts(String search,boolean history){if(!canUse()){showLockedScreen(false);return;}prepare("Estoque",()->showProducts(search,false),history);EditText q=input("Pesquisar produto, categoria ou código");q.setText(search);Button find=button("Buscar",C.blue);find.setOnClickListener(v->showProducts(q.getText().toString(),false));LinearLayout searchBar=responsiveRow();searchBar.addView(q,cellGrow());searchBar.addView(find,cellFixed(105));content.addView(searchBar,full());Button add=button("+ Cadastrar produto",C.green);add.setOnClickListener(v->showProductForm(null,true));content.addView(add,full());Cursor c=db.products(search);if(c.getCount()==0)content.addView(empty("Nenhum produto encontrado."),full());while(c.moveToNext()){long id=c.getLong(c.getColumnIndexOrThrow("id"));String name=c.getString(c.getColumnIndexOrThrow("name"));String cat=c.getString(c.getColumnIndexOrThrow("category"));double stock=c.getDouble(c.getColumnIndexOrThrow("stock")),min=c.getDouble(c.getColumnIndexOrThrow("min_stock")),price=c.getDouble(c.getColumnIndexOrThrow("price"));String unit=c.getString(c.getColumnIndexOrThrow("unit"));boolean lowStock=stock<=min;LinearLayout card=card(lowStock?0xFFFFF7ED:Color.WHITE,lowStock?C.orange:0xFFE2E8F0);card.addView(tv(name,18,true,C.text));if(!cat.isEmpty())card.addView(tv(cat,12,false,C.muted));LinearLayout metrics=responsiveRow();metrics.addView(metric("Estoque",DatabaseHelper.formatNumber(stock)+" "+unit,lowStock?C.red:C.green),cell());metrics.addView(metric("Mínimo",DatabaseHelper.formatNumber(min)+" "+unit,C.text),cell());metrics.addView(metric("Venda",DatabaseHelper.money(price),C.blue),cell());card.addView(metrics,full());LinearLayout buttons=responsiveRow();Button entry=button("Entrada",C.green);entry.setOnClickListener(v->stockDialog(id,name,true));Button adjust=button("Ajuste",C.orange);adjust.setOnClickListener(v->stockDialog(id,name,false));Button edit=button("Editar",C.blue);edit.setOnClickListener(v->showProductForm(id,true));Button del=button("Arquivar",C.red);del.setOnClickListener(v->confirmArchiveProduct(id,name));buttons.addView(entry,cell());buttons.addView(adjust,cell());buttons.addView(edit,cell());buttons.addView(del,cell());card.addView(buttons,full());content.addView(card,full());}c.close();}

    private void showProductForm(Long id,boolean history){if(!canUse()){showLockedScreen(false);return;}prepare(id==null?"Novo produto":"Editar produto",()->showProductForm(id,false),history);EditText name=input("Nome do produto");EditText category=input("Categoria");EditText barcode=input("Código de barras");EditText cost=num("Custo");EditText price=num("Preço de venda");EditText stock=num("Estoque atual");EditText min=num("Estoque mínimo");EditText unit=input("Unidade (un, lata, garrafa, kg...)");unit.setText("un");if(id!=null){Cursor c=db.product(id);if(c.moveToFirst()){name.setText(c.getString(c.getColumnIndexOrThrow("name")));category.setText(c.getString(c.getColumnIndexOrThrow("category")));barcode.setText(c.getString(c.getColumnIndexOrThrow("barcode")));cost.setText(DatabaseHelper.formatNumber(c.getDouble(c.getColumnIndexOrThrow("cost"))));price.setText(DatabaseHelper.formatNumber(c.getDouble(c.getColumnIndexOrThrow("price"))));stock.setText(DatabaseHelper.formatNumber(c.getDouble(c.getColumnIndexOrThrow("stock"))));min.setText(DatabaseHelper.formatNumber(c.getDouble(c.getColumnIndexOrThrow("min_stock"))));unit.setText(c.getString(c.getColumnIndexOrThrow("unit")));}c.close();}
        content.addView(field("Produto",name));content.addView(field("Categoria",category));content.addView(field("Código",barcode));LinearLayout values=responsiveRow();values.addView(field("Custo",cost),cell());values.addView(field("Preço",price),cell());content.addView(values,full());LinearLayout inventory=responsiveRow();inventory.addView(field("Estoque",stock),cell());inventory.addView(field("Mínimo",min),cell());inventory.addView(field("Unidade",unit),cell());content.addView(inventory,full());Button save=button("Salvar produto",C.dark);save.setOnClickListener(v->{String n=name.getText().toString().trim();if(n.isEmpty()){toast("Informe o nome do produto.");name.requestFocus();return;}String u=unit.getText().toString().trim();if(u.isEmpty())u="un";try{if(!canUse()){showLockedScreen(false);return;}db.saveProduct(id,n,category.getText().toString().trim(),barcode.getText().toString().trim(),value(cost),value(price),Math.max(0,value(stock)),Math.max(0,value(min)),u,iso.format(new Date()));if(id==null){license.startTrialIfNeeded();updateLicenseStatus();}toast("Produto salvo com sucesso.");showProducts("",false);}catch(Exception e){error(e);}});content.addView(save,full());}

    private void stockDialog(long id,String name,boolean entry){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(20),dp(6),dp(20),0);EditText qty=num(entry?"Quantidade de entrada":"Use positivo para entrada ou negativo para saída");if(!entry)qty.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL|InputType.TYPE_NUMBER_FLAG_SIGNED);EditText reason=input("Motivo / observação");box.addView(qty,full());box.addView(reason,full());AlertDialog dialog=new AlertDialog.Builder(this).setTitle((entry?"Entrada de estoque: ":"Ajuste de estoque: ")+name).setView(box).setNegativeButton("Cancelar",null).setPositiveButton("Salvar",null).create();dialog.setOnShowListener(x->dialog.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{double amount=value(qty);if(entry)amount=Math.abs(amount);try{db.adjustStock(id,amount,entry?"ENTRADA":"AJUSTE",reason.getText().toString().trim(),iso.format(new Date()));dialog.dismiss();toast("Estoque atualizado.");showProducts("",false);}catch(Exception e){toast(e.getMessage());}}));dialog.show();}
    private void confirmArchiveProduct(long id,String name){new AlertDialog.Builder(this).setTitle("Arquivar produto?").setMessage(name+" deixará de aparecer nas vendas e no estoque. O histórico anterior será mantido.").setNegativeButton("Cancelar",null).setPositiveButton("Arquivar",(d,w)->{db.archiveProduct(id);toast("Produto arquivado.");showProducts("",false);}).show();}

    private void showSale(boolean history){if(!canUse()){showLockedScreen(false);return;}prepare("Nova venda",()->showSale(false),history);cartClear();Cursor c=db.products("");ArrayList<ProductOption> options=new ArrayList<>();while(c.moveToNext())options.add(new ProductOption(c.getLong(c.getColumnIndexOrThrow("id")),c.getString(c.getColumnIndexOrThrow("name")),c.getDouble(c.getColumnIndexOrThrow("price")),c.getDouble(c.getColumnIndexOrThrow("stock")),c.getString(c.getColumnIndexOrThrow("unit"))));c.close();if(options.isEmpty()){content.addView(empty("Cadastre um produto antes de realizar uma venda."),full());Button go=button("Cadastrar produto",C.blue);go.setOnClickListener(v->showProductForm(null,true));content.addView(go,full());return;}
        Spinner product=new Spinner(this);ArrayList<String> labels=new ArrayList<>();for(ProductOption p:options)labels.add(p.name+" • estoque "+DatabaseHelper.formatNumber(p.stock)+" "+p.unit);product.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,labels));EditText qty=num("Quantidade");qty.setText("1");EditText unitPrice=num("Preço unitário");product.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onNothingSelected(android.widget.AdapterView<?> p){}public void onItemSelected(android.widget.AdapterView<?> p,View v,int pos,long i){unitPrice.setText(DatabaseHelper.formatNumber(options.get(pos).price));}});content.addView(field("Produto",product));LinearLayout qp=responsiveRow();qp.addView(field("Quantidade",qty),cell());qp.addView(field("Preço unitário",unitPrice),cell());content.addView(qp,full());Button add=button("Adicionar ao carrinho",C.blue);content.addView(add,full());LinearLayout cartBox=card(Color.WHITE,0xFFE2E8F0);content.addView(cartBox,full());Spinner payment=new Spinner(this);payment.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"Dinheiro","PIX","Cartão","Fiado","Outro"}));EditText notes=input("Observações da venda");content.addView(field("Pagamento",payment));content.addView(field("Observações",notes));Button finish=button("Finalizar venda",C.green);content.addView(finish,full());Runnable render=()->renderCart(cartBox);
        add.setOnClickListener(v->{int pos=product.getSelectedItemPosition();if(pos<0)return;ProductOption p=options.get(pos);double q=value(qty),price=value(unitPrice);if(q<=0){toast("Informe uma quantidade maior que zero.");return;}if(price<0){toast("Preço inválido.");return;}double already=cartQuantity(p.id);if(already+q>p.stock+0.000001){toast("Estoque insuficiente. Disponível: "+DatabaseHelper.formatNumber(p.stock)+" "+p.unit+"; no carrinho: "+DatabaseHelper.formatNumber(already));return;}try{JSONObject o=new JSONObject();o.put("productId",p.id);o.put("productName",p.name);o.put("quantity",q);o.put("unitPrice",price);o.put("subtotal",round2(q*price));cart.put(o);qty.setText("1");render.run();}catch(Exception e){error(e);}});
        finish.setOnClickListener(v->{if(!canUse()){showLockedScreen(false);return;}if(cart.length()==0){toast("Adicione pelo menos um item.");return;}new AlertDialog.Builder(this).setTitle("Finalizar venda?").setMessage("Total: "+DatabaseHelper.money(cartTotal())+"\nPagamento: "+payment.getSelectedItem()).setNegativeButton("Cancelar",null).setPositiveButton("Finalizar",(d,w)->{try{long id=db.createSale(cart,payment.getSelectedItem().toString(),notes.getText().toString().trim(),iso.format(new Date()));toast("Venda #"+id+" finalizada.");cartClear();showDashboard(false);}catch(Exception e){error(e);}}).show();});render.run();}

    private void renderCart(LinearLayout box){box.removeAllViews();box.addView(section("Carrinho"));if(cart.length()==0){box.addView(tv("Nenhum item adicionado.",14,false,C.muted));return;}for(int i=0;i<cart.length();i++){try{JSONObject o=cart.getJSONObject(i);int idx=i;LinearLayout item=horizontal(false);TextView t=tv(o.getString("productName")+"\n"+DatabaseHelper.formatNumber(o.getDouble("quantity"))+" × "+DatabaseHelper.money(o.getDouble("unitPrice"))+" = "+DatabaseHelper.money(o.getDouble("subtotal")),14,true,C.text);item.addView(t,new LinearLayout.LayoutParams(0,-2,1));Button remove=button("Remover",C.red);remove.setOnClickListener(v->{cart.remove(idx);renderCart(box);});item.addView(remove,new LinearLayout.LayoutParams(dp(95),dp(44)));box.addView(item,full());}catch(Exception ignored){}}TextView total=tv("TOTAL  "+DatabaseHelper.money(cartTotal()),22,true,C.green);total.setGravity(Gravity.END);box.addView(total,full());}
    private double cartQuantity(long id){double q=0;for(int i=0;i<cart.length();i++)q+=cart.optJSONObject(i)!=null&&cart.optJSONObject(i).optLong("productId")==id?cart.optJSONObject(i).optDouble("quantity"):0;return q;}
    private double cartTotal(){double t=0;for(int i=0;i<cart.length();i++)t+=cart.optJSONObject(i)==null?0:cart.optJSONObject(i).optDouble("subtotal");return round2(t);}
    private void cartClear(){while(cart.length()>0)cart.remove(0);}

    private void showReports(boolean history){if(!canUse()){showLockedScreen(false);return;}prepare("Relatórios",()->showReports(false),history);Button daily=button("Vendas diárias",C.blue);daily.setOnClickListener(v->showDailyReport(day.format(new Date()),true));Button buy=button("O que precisa comprar",C.orange);buy.setOnClickListener(v->showBuyReport(true));Button historyBtn=button("Histórico de vendas",C.dark);historyBtn.setOnClickListener(v->showSalesHistory(true));content.addView(daily,full());content.addView(buy,full());content.addView(historyBtn,full());}
    private void showDailyReport(String date,boolean history){if(!canUse()){showLockedScreen(false);return;}prepare("Vendas do dia",()->showDailyReport(date,false),history);Button choose=button("Data: "+formatDay(date),C.blue);choose.setOnClickListener(v->{Calendar cal=Calendar.getInstance();new DatePickerDialog(this,(p,y,m,d)->showDailyReport(String.format(Locale.US,"%04d-%02d-%02d",y,m+1,d),false),cal.get(Calendar.YEAR),cal.get(Calendar.MONTH),cal.get(Calendar.DAY_OF_MONTH)).show();});content.addView(choose,full());LinearLayout stats=responsiveRow();stats.addView(stat("Total",DatabaseHelper.money(db.dailyTotal(date))),cell());stats.addView(stat("Vendas",String.valueOf(db.dailyCount(date))),cell());content.addView(stats,full());content.addView(section("Por forma de pagamento"));Cursor pay=db.paymentSummary(date);if(pay.getCount()==0)content.addView(empty("Nenhuma venda nesta data."),full());while(pay.moveToNext())content.addView(metric(pay.getString(0),pay.getInt(1)+" venda(s) • "+DatabaseHelper.money(pay.getDouble(2)),C.blue),full());pay.close();content.addView(section("Produtos mais vendidos"));Cursor top=db.topProducts(date);while(top.moveToNext())content.addView(metric(top.getString(0),DatabaseHelper.formatNumber(top.getDouble(1))+" un • "+DatabaseHelper.money(top.getDouble(2)),C.green),full());top.close();content.addView(section("Vendas"));renderSales(db.salesForDay(date));}
    private void showBuyReport(boolean history){if(!canUse()){showLockedScreen(false);return;}prepare("Lista de compras",()->showBuyReport(false),history);Cursor c=db.lowStockProducts();if(c.getCount()==0)content.addView(empty("Nenhum produto abaixo do estoque mínimo."),full());while(c.moveToNext()){LinearLayout card=card(0xFFFFF7ED,C.orange);String name=c.getString(c.getColumnIndexOrThrow("name"));double stock=c.getDouble(c.getColumnIndexOrThrow("stock")),min=c.getDouble(c.getColumnIndexOrThrow("min_stock")),suggest=c.getDouble(c.getColumnIndexOrThrow("suggested"));String unit=c.getString(c.getColumnIndexOrThrow("unit"));card.addView(tv(name,18,true,C.red));card.addView(tv("Atual: "+DatabaseHelper.formatNumber(stock)+" "+unit+"\nMínimo: "+DatabaseHelper.formatNumber(min)+" "+unit+"\nComprar: "+DatabaseHelper.formatNumber(suggest)+" "+unit,14,false,C.text));content.addView(card,full());}c.close();}
    private void showSalesHistory(boolean history){if(!canUse()){showLockedScreen(false);return;}prepare("Histórico de vendas",()->showSalesHistory(false),history);renderSales(db.allSales());}
    private void renderSales(Cursor c){if(c.getCount()==0)content.addView(empty("Nenhuma venda encontrada."),full());while(c.moveToNext()){long id=c.getLong(c.getColumnIndexOrThrow("id"));String at=c.getString(c.getColumnIndexOrThrow("sold_at"));double total=c.getDouble(c.getColumnIndexOrThrow("total"));String pay=c.getString(c.getColumnIndexOrThrow("payment_method"));int count=c.getInt(c.getColumnIndexOrThrow("item_count"));LinearLayout card=card(Color.WHITE,0xFFE2E8F0);card.addView(tv("Venda #"+id+" • "+DatabaseHelper.money(total),17,true,C.text));card.addView(tv(formatDate(at)+" • "+pay+" • "+count+" item(ns)",13,false,C.muted));Button details=button("Ver detalhes",C.blue);details.setOnClickListener(v->showSaleItems(id,total,true));card.addView(details,full());content.addView(card,full());}c.close();}
    private void showSaleItems(long saleId,double total,boolean history){if(!canUse()){showLockedScreen(false);return;}prepare("Venda #"+saleId,()->showSaleItems(saleId,total,false),history);Cursor c=db.saleItems(saleId);while(c.moveToNext()){LinearLayout item=card(Color.WHITE,0xFFE2E8F0);item.addView(tv(c.getString(c.getColumnIndexOrThrow("product_name")),16,true,C.text));item.addView(tv(DatabaseHelper.formatNumber(c.getDouble(c.getColumnIndexOrThrow("quantity")))+" × "+DatabaseHelper.money(c.getDouble(c.getColumnIndexOrThrow("unit_price")))+" = "+DatabaseHelper.money(c.getDouble(c.getColumnIndexOrThrow("subtotal"))),14,false,C.muted));content.addView(item,full());}c.close();content.addView(stat("Total da venda",DatabaseHelper.money(total)),full());}

    private void showLockedScreen(boolean history){prepare("Versão de demonstração",()->showLockedScreen(false),history);backStack.clear();LinearLayout lock=card(0xFFFFF1F2,C.red);TextView icon=tv("🔒",48,true,C.red);icon.setGravity(Gravity.CENTER);lock.addView(icon,full());TextView title=tv("O período de 3 dias terminou",22,true,C.text);title.setGravity(Gravity.CENTER);lock.addView(title,full());TextView msg=tv("O aplicativo foi bloqueado para novos lançamentos. Seus produtos, estoque, vendas e relatórios permanecem salvos no celular e serão mantidos após a ativação PRO.",14,false,C.text);msg.setGravity(Gravity.CENTER);lock.addView(msg,full());lock.addView(tv("Início da demonstração: "+license.formattedStart()+"\nTérmino: "+license.formattedEnd(),12,true,C.muted),full());Button unlock=button("Desbloquear versão PRO",C.green);unlock.setOnClickListener(v->showUnlockDialog());lock.addView(unlock,full());Button backup=button("Exportar meus dados",C.blue);backup.setOnClickListener(v->exportLauncher.launch("backup_controle_bar_"+day.format(new Date())+".json"));lock.addView(backup,full());Button guide=button("Abrir guia",C.orange);guide.setOnClickListener(v->startActivity(new Intent(this,GuideActivity.class)));lock.addView(guide,full());content.addView(lock,full());}

    private void showUnlockDialog(){EditText password=input("Digite a senha de desbloqueio");password.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(20),dp(6),dp(20),0);box.addView(tv("A ativação mantém todos os dados já cadastrados.",13,false,C.muted),full());box.addView(password,full());AlertDialog dialog=new AlertDialog.Builder(this).setTitle("Desbloquear versão PRO").setView(box).setNegativeButton("Cancelar",null).setPositiveButton("Desbloquear",null).create();dialog.setOnShowListener(x->dialog.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{if(license.unlock(password.getText().toString())){dialog.dismiss();updateLicenseStatus();backStack.clear();toast("Versão PRO ativada. Todos os dados foram mantidos.");showDashboard(false);}else{password.setError("Senha incorreta");password.requestFocus();}}));dialog.show();}

    private void showMore(boolean history){prepare("Mais opções",()->showMore(false),history);LinearLayout licenseCard=card(license.isPro()?0xFFF0FDF4:(license.isExpired()?0xFFFFF1F2:0xFFFFFBEB),license.isPro()?C.green:(license.isExpired()?C.red:C.orange));licenseCard.addView(tv(license.isPro()?"VERSÃO PRO ATIVA":license.statusLabel(),17,true,license.isPro()?C.green:(license.isExpired()?C.red:C.orange)));String licenseText=license.isPro()?"Licença liberada neste aparelho. Produtos, estoque e vendas permanecem no SQLite local.":(!license.isTrialStarted()?"Os 3 dias começam no primeiro produto cadastrado.":"Início: "+license.formattedStart()+"\nTérmino: "+license.formattedEnd());licenseCard.addView(tv(licenseText,13,false,C.text));if(!license.isPro()){Button unlock=button(license.isExpired()?"Desbloquear agora":"Ativar versão PRO",C.green);unlock.setOnClickListener(v->showUnlockDialog());licenseCard.addView(unlock,full());}content.addView(licenseCard,full());Button exp=button("Exportar todos os dados",C.blue);exp.setOnClickListener(v->exportLauncher.launch("backup_controle_bar_"+day.format(new Date())+".json"));Button imp=button("Importar backup completo",C.green);imp.setOnClickListener(v->importLauncher.launch(new String[]{"application/json","text/plain"}));Button guide=button("Abrir guia interativo com voz",C.orange);guide.setOnClickListener(v->startActivity(new Intent(this,GuideActivity.class)));content.addView(exp,full());content.addView(imp,full());content.addView(guide,full());TextView warning=tv("A importação substitui todos os dados atuais. Exporte um backup antes. A licença PRO não é apagada pela importação.",13,true,C.red);warning.setBackground(bg(0xFFFFF1F2,C.red,14));warning.setPadding(dp(12),dp(12),dp(12),dp(12));content.addView(warning,full());}
    private void exportTo(Uri uri){try(OutputStream out=getContentResolver().openOutputStream(uri)){if(out==null)throw new Exception("Não foi possível abrir o arquivo.");JSONObject root=db.exportAll();root.put("exportedAt",iso.format(new Date()));out.write(root.toString(2).getBytes(StandardCharsets.UTF_8));toast("Backup exportado com sucesso.");}catch(Exception e){error(e);}}
    private void confirmImport(Uri uri){new AlertDialog.Builder(this).setTitle("Restaurar backup?").setMessage("Todos os dados atuais serão substituídos. Esta ação não pode ser desfeita.").setNegativeButton("Cancelar",null).setPositiveButton("Importar",(d,w)->importFrom(uri)).show();}
    private void importFrom(Uri uri){try(BufferedReader r=new BufferedReader(new InputStreamReader(Objects.requireNonNull(getContentResolver().openInputStream(uri)),StandardCharsets.UTF_8))){StringBuilder s=new StringBuilder();String line;while((line=r.readLine())!=null)s.append(line);db.importAll(new JSONObject(s.toString()));if(db.productCount()>0)license.startTrialIfNeeded();updateLicenseStatus();backStack.clear();toast("Backup restaurado com sucesso.");if(license.isExpired())showLockedScreen(false);else showDashboard(false);}catch(Exception e){error(e);}}

    private LinearLayout card(int fill,int stroke){LinearLayout v=new LinearLayout(this);v.setOrientation(LinearLayout.VERTICAL);v.setPadding(dp(14),dp(14),dp(14),dp(14));v.setBackground(bg(fill,stroke,18));v.setElevation(dp(2));return v;}
    private View stat(String label,String value){LinearLayout c=card(Color.WHITE,0xFFE2E8F0);c.addView(tv(label.toUpperCase(),11,true,C.muted));c.addView(tv(value,20,true,C.text));return c;}
    private View metric(String label,String value,int valueColor){LinearLayout c=card(Color.WHITE,0xFFE2E8F0);c.addView(tv(label,12,true,C.muted));c.addView(tv(value,15,true,valueColor));return c;}
    private TextView section(String s){TextView t=tv(s,17,true,C.text);t.setPadding(dp(2),dp(14),0,dp(5));return t;}
    private TextView empty(String s){TextView t=tv(s,14,true,C.muted);t.setGravity(Gravity.CENTER);t.setPadding(dp(18),dp(24),dp(18),dp(24));t.setBackground(bg(Color.WHITE,0xFFCBD5E1,16));return t;}
    private LinearLayout field(String label,View input){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.addView(tv(label,12,true,C.text));box.addView(input,new LinearLayout.LayoutParams(-1,dp(50)));return box;}
    private LinearLayout responsiveRow(){LinearLayout l=new LinearLayout(this);l.setOrientation(isCompact()?LinearLayout.VERTICAL:LinearLayout.HORIZONTAL);l.setGravity(Gravity.CENTER_VERTICAL);return l;}
    private LinearLayout horizontal(boolean verticalOnCompact){LinearLayout l=new LinearLayout(this);l.setOrientation(verticalOnCompact&&isCompact()?LinearLayout.VERTICAL:LinearLayout.HORIZONTAL);l.setGravity(Gravity.CENTER_VERTICAL);return l;}
    private Button button(String s,int color){Button b=new Button(this);b.setText(s);b.setTextColor(Color.WHITE);b.setTextSize(12);b.setAllCaps(false);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setGravity(Gravity.CENTER);b.setBackground(bg(color,color,12));b.setPadding(dp(8),0,dp(8),0);b.setMinHeight(dp(44));return b;}
    private EditText input(String hint){EditText e=new EditText(this);e.setHint(hint);e.setTextSize(15);e.setSingleLine();e.setTextColor(C.text);e.setHintTextColor(0xFF94A3B8);e.setBackground(bg(Color.WHITE,0xFFCBD5E1,12));e.setPadding(dp(12),0,dp(12),0);return e;}
    private EditText num(String hint){EditText e=input(hint);e.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);return e;}
    private TextView tv(String s,int size,boolean bold,int color){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);if(bold)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);t.setPadding(dp(3),dp(3),dp(3),dp(3));return t;}
    private GradientDrawable bg(int fill,int stroke,int radius){GradientDrawable g=new GradientDrawable();g.setColor(fill);g.setCornerRadius(dp(radius));g.setStroke(dp(1),stroke);return g;}
    private LinearLayout.LayoutParams full(){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(5),0,dp(5));return p;}
    private LinearLayout.LayoutParams cell(){LinearLayout.LayoutParams p=isCompact()?new LinearLayout.LayoutParams(-1,-2):new LinearLayout.LayoutParams(0,-2,1);p.setMargins(dp(3),dp(3),dp(3),dp(3));return p;}
    private LinearLayout.LayoutParams cellGrow(){return cell();}
    private LinearLayout.LayoutParams cellFixed(int width){LinearLayout.LayoutParams p=isCompact()?new LinearLayout.LayoutParams(-1,dp(48)):new LinearLayout.LayoutParams(dp(width),dp(48));p.setMargins(dp(3),dp(3),dp(3),dp(3));return p;}
    private boolean isCompact(){return getResources().getConfiguration().screenWidthDp<600;}
    private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
    private double value(EditText e){try{return Double.parseDouble(e.getText().toString().trim().replace(',','.'));}catch(Exception x){return 0;}}
    private double round2(double v){return Math.round(v*100.0)/100.0;}
    private String formatDate(String s){try{return br.format(Objects.requireNonNull(iso.parse(s)));}catch(Exception e){return s;}}
    private String formatDay(String s){try{return new SimpleDateFormat("dd/MM/yyyy",new Locale("pt","BR")).format(Objects.requireNonNull(day.parse(s)));}catch(Exception e){return s;}}
    private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
    private void error(Exception e){new AlertDialog.Builder(this).setTitle("Não foi possível concluir").setMessage(e.getMessage()==null?"Erro inesperado.":e.getMessage()).setPositiveButton("OK",null).show();}

    private static class ProductOption{final long id;final String name;final double price,stock;final String unit;ProductOption(long id,String name,double price,double stock,String unit){this.id=id;this.name=name;this.price=price;this.stock=stock;this.unit=unit;}}
    private static class C{static final int bg=0xFFF3F4F6,text=0xFF111827,muted=0xFF64748B,dark=0xFF111827,nav=0xFF1F2937,blue=0xFF2563EB,green=0xFF16A34A,orange=0xFFD97706,red=0xFFDC2626,gray=0xFF475569;}
}
